config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "mains#index"
  resources :mains, only: :index
  resources :users, only: [:show, :edit, :update]
  resources :staffs
  resources :hair_styles
  resources :reservations, only: [:index, :new, :create, :show]
  resources :news
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position

  with_options presence: true do
    validates :name
    validates :position_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :hobby
    validates :introduction
    validates :image
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_staff, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:new, :create, :edit, :update, :destroy]

  def index
    @staffs = Staff.order('position_id ASC')
  end

  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new(staff_params)
    if @staff.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @staff.update(staff_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    @staff.destroy
    redirect_to action: :index
  end

  private

  def staff_params
    params.require(:staff).permit(:name, :position_id, :hobby, :introduction, :image).merge(user_id: current_user.id)
  end

  def find_staff
    @staff = Staff.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.admin?
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/edit.html.erb
<%= render 'shared/header' %>

<div class="contents row">
  <h2>Edit Staff</h2>
  <div class="container">
    <%= form_with model: @staff, url: staff_path(@staff.id), id: 'edit_staff', class: 'edit_staff', local: true do |f| %>

      <div class="field">
        <%= f.label :image %><br />
        <%= f.file_field :image %>
      </div>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_area :name %>
      </div>

      <div class="field">
        <%= f.label :position %><br />
        <%= f.collection_select(:position_id, Position.all, :id, :name, {}, {class:"position-select"}) %>
      </div>

      <div class="field">
        <%= f.label :hobby %><br />
        <%= f.text_area :hobby %>
      </div>

      <div class="field">
        <%= f.label :introduction %><br />
        <%= f.text_area :introduction %>
      </div>

      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/staffs/index.html.erb
<%= render 'shared/header' %>

<div class="staffs">
  <h1 class="staff-title">STAFF</h1>
  <% @staffs.each do |staff| %>
    <div class="staff">
      <div class="staff-image">
        <%= link_to image_tag(staff.image, class:"img"), staff_path(staff.id) %>
      </div> 
      <div class="staff-name">
        <i class="fa-solid fa-scissors"></i><%= staff.name %>
      </div>
      <div class="staff-position">
        <i class="fa-solid fa-scissors"></i><%= staff.position.name %>
      </div>
    </div>
  <% end %>
  <% if user_signed_in? && current_user.admin? %>
    <div class='create-btn'>
      <%= link_to 'Create', new_staff_path %>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>

app/views/staffs/new.html.erb
<%= render 'shared/header' %>

<div class="contents row">
  <h2>Create Staff</h2>
  <div class="container">
    <%= form_with model: @staff, url: staffs_path, id: 'new_staff', class: 'new_staff', local: true do |f| %>

      <div class="field">
        <%= f.label :image %><br />
        <%= f.file_field :image %>
      </div>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_area :name %>
      </div>

      <div class="field">
        <%= f.label :position %><br />
        <%= f.collection_select(:position_id, Position.all, :id, :name, {}, {class:"position-select"}) %>
      </div>

      <div class="field">
        <%= f.label :hobby %><br />
        <%= f.text_area :hobby %>
      </div>

      <div class="field">
        <%= f.label :introduction %><br />
        <%= f.text_area :introduction %>
      </div>

      <div class="actions">
        <%= f.submit "Addition" %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/staffs/show.html.erb
<%= render 'shared/header' %>

<div class="staff-details">
  <h1 class="staff-detail-title">STAFF</h1>
  <div class="staff-detail">
    <div class="left-detail">
      <%= image_tag @staff.image, class: "staff-detail-image" %>
    </div>
    <div class="right-detail">
      <div class="staff-detail-name">
        <%= @staff.name %>
      </div>
      <div class="staff-detail-position">
        <%= @staff.position.name %>
      </div>
      <div class="staff-detail-hobby">
        <i class="fa-solid fa-scissors"></i>hobby： <%= @staff.hobby %>
      </div>
      <div class="staff-detail-introduction">
        <i class="fa-solid fa-scissors"></i>comment：<br><%= @staff.introduction %>
      </div>
      <div class="staff-detail-sns">
        <div class="upper-sns">
          <div class="staff-twitter">
            <a href="#"><i class="fa-brands fa-twitter fa-fw"></i>Twitter</a>
          </div>
          <div class="staff-facebook">
            <a href="#"><i class="fa-brands fa-facebook fa-fw"></i>facebook</a>
          </div>
        </div>
        <div class="bottom-sns">
          <div class="staff-instagram">
            <a href="#"><i class="fa-brands fa-instagram fa-fw"></i>Instagram</a>
          </div>
          <div class="staff-youtube">
            <a href="#"><i class="fa-brands fa-youtube fa-fw"></i>YouTube</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% if user_signed_in? && current_user.admin? %>
    <div class="staff-detail-btn">
      <div class='edit-delete-btn'>
        <%= link_to 'Edit', edit_staff_path(@staff.id) %>
      </div>
      <div class='edit-delete-btn'>
        <%= link_to 'Delete', staff_path(@staff.id), method: :delete %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>