config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "mains#index"
  resources :mains, only: :index
  resources :users, only: [:show, :edit, :update]
  resources :staffs
  resources :hair_styles
  resources :reservations, only: [:index, :new, :create, :show]
  resources :news
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'MENS' },
    { id: 3, name: 'LADIES' }
  ]

  include ActiveHash::Associations
  has_many :hair_styles
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ベリーショート' },
    { id: 3, name: 'ショート' },
    { id: 4, name: 'ボブ' },
    { id: 5, name: 'ミディアム' },
    { id: 6, name: 'セミロング' },
    { id: 7, name: 'ロング' },
    { id: 8, name: 'スーパーロング' },
    { id: 9, name: 'ビジネス' },
    { id: 10, name: '大人' }
  ]

  include ActiveHash::Associations
  has_many :hair_styles
end

app/models/hair_style.rb
class HairStyle < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :genre

  with_options presence: true do
    validates :style_name
    validates :gender_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :genre_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :images
  end
end

app/models/new.rb
class New < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :content
  end
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '店長' },
    { id: 3, name: 'ディレクター' },
    { id: 4, name: 'トップスタイリスト' },
    { id: 5, name: 'スタイリスト' },
    { id: 6, name: 'アシスタント' }
  ]

  include ActiveHash::Associations
  has_many :staffs
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user

  validate :date_before_start
  validate :date_current_today
  validate :date_three_month_end

  def date_before_start
    errors.add(:day, 'は過去の日付は選択できません') if day < Date.current
  end

  def date_current_today
    errors.add(:day, 'は当日は選択できません。予約画面から正しい日付を選択してください。') if day < (Date.current + 1)
  end

  def date_three_month_end
    errors.add(:day, 'は3ヶ月以降の日付は選択できません') if (Date.current >> 3) < day
  end

  def self.reservations_after_three_month
    reservations = Reservation.all.where('day >= ?', Date.current).where('day < ?', Date.current >> 3).order(day: :desc)
    reservation_data = []
    reservations.each do |reservation|
      reservations_hash = {}
      reservations_hash.merge!(day: reservation.day.strftime('%Y-%m-%d'), time: reservation.time)
      reservation_data.push(reservations_hash)
    end
    reservation_data
  end

  def self.check_reservation_day(day)
    if day < Date.current
      '過去の日付は選択できません。正しい日付を選択してください。'
    elsif day < (Date.current + 1)
      '当日は選択できません。正しい日付を選択してください。'
    elsif (Date.current >> 3) < day
      '3ヶ月以降の日付は選択できません。正しい日付を選択してください。'
    end
  end
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true  # optional: trueで、レコードを保存する際に、外部キーの値がない場合でも保存ができる
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position

  with_options presence: true do
    validates :name
    validates :position_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :hobby
    validates :introduction
    validates :image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :nickname, presence: true
  validates :birthday, presence: true

  has_many :sns_credentials
  has_many :staffs
  has_many :hair_styles
  has_many :reservations
  has_many :news

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    # userが登録済みであるか判断
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def index
    @hairs = HairStyle.order('created_at DESC')
    @news = New.order('updated_at DESC')
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_news, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:new, :create, :edit, :update, :destroy]

  def index
    @news = New.order('updated_at DESC').page(params[:page]).per(5)
  end

  def new
    @new = New.new
  end

  def create
    @new = New.new(new_params)
    if @new.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @new.update(new_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    @new.destroy
    redirect_to action: :index
  end

  private

  def new_params
    params.require(:new).permit(:title, :content).merge(user_id: current_user.id)
  end

  def find_news
    @new = New.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :move_to_root

  def show
    move_to_root
  end

  def edit
    move_to_root
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {}).permit(:nickname, :email)
  end

  def move_to_root
    set_user
    redirect_to root_path unless @user == current_user || current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hair_styles_helper.rb
module HairStylesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def times
    times = ['11:00',
             '11:30',
             '12:00',
             '12:30',
             '13:00',
             '13:30',
             '14:00',
             '14:30',
             '15:00',
             '15:30',
             '16:00',
             '16:30',
             '17:00',
             '17:30',
             '18:00',
             '18:30',
             '19:00',
             '19:30',
             '20:00',
             '20:30',
             '21:00',
             '21:30']
  end

  def check_reservation(reservations, day, time)
    result = false
    reservations_count = reservations.count  # 取得した予約データにdayとtimeが一致する場合はtrue,一致しない場合はfalseを返す
    if reservations_count > 1
      reservations.each do |reservation|
        result = reservation[:day].eql?(day.strftime('%Y-%m-%d')) && reservation[:time].eql?(time)
        return result if result
      end
    elsif reservations_count == 1
      result = reservations[0][:day].eql?(day.strftime('%Y-%m-%d')) && reservations[0][:time].eql?(time)
      return result if result
    end
    result
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalonApp</title>
    <meta name="discription" content="おしゃれなサロンのサイトです">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v6.1.1/css/all.css" rel="stylesheet">
    <%# <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-nav">
    <div class="left-nav">
      <ul>
        <li><a><%= link_to 'HOME', '/' %></a></li>
        <li><a><%= link_to 'NEWS', new_news_path %></a></li>
        <li><a><%= link_to 'CONCEPT', '#' %></a></li>
      </ul>
      <ul>
        <li><a><%= link_to 'MENU', news_index_path %></a></li>
        <li><a><%= link_to 'HAIR STYLE', hair_styles_path %></a></li>
        <li><a><%= link_to 'STAFF', staffs_path %></a></li>
      </ul>
      <ul>
        <li><a><%= link_to 'BLOG', '#' %></a></li>
        <li><a><%= link_to 'ACCESS', '#' %></a></li>
        <li><a><%= link_to 'RESERVE', reservations_path %></a></li>
      </ul>
    </div>
    <div class="right-nav">
      <ul>
        <li><a><i class="fa-brands fa-twitter"></i><%= link_to 'Twitter', '#' %></a></li>
        <li><a><i class="fa-brands fa-facebook"></i><%= link_to 'facebook', '#' %></a></li>
        <li><a><i class="fa-brands fa-instagram"></i><%= link_to 'Instagram', '#' %></a></li>
      </ul>
    </div>
  </div>

  <div class="copyright">
    <div>©︎2022 CHILLOUT HAIR & BEAUTY</div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-top">
    <h1>CHILLOUT<br><span>HAIR & BEAUTY</span></h1>

    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'Log in', new_user_session_path, class: "login" %></li>
        <li><%= link_to 'Sign up', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>

  <ul class="globalNavi">
    <li><a><%= link_to 'HOME', '/' %></a></li>
    <li><a><%= link_to 'NEWS', news_index_path %></a></li>
    <li><a><%= link_to 'CONCEPT', '#' %></a></li>
    <li><a><%= link_to 'MENU', '#' %></a></li>
    <li><a><%= link_to 'HAIR STYLE', hair_styles_path %></a></li>
    <li><a><%= link_to 'STAFF', staffs_path %></a></li>
    <li><a><%= link_to 'BLOG', '#' %></a></li>
    <li><a><%= link_to 'ACCESS', '#' %></a></li>
    <li><a><%= link_to 'RESERVE', reservations_path %></a></li>
  </ul>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <% else %>
      <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
    <% reservations = Reservation.reservations_after_three_month %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>TIME</th>
        <% date_range.slice(0, 7).each do |day| %>
          <th width="12%"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <td></td>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
        <% times.each do |time| %>
          <tr>
            <td><%= time %></td>
            <% week.each do |day| %>
              <td>
                <% if check_reservation(reservations, day, time) %>
                  <%= '✖️' %>
                <% else %>
                  <%= link_to new_reservation_path(day: day, time: time) do %>
                    <%= '○' %>
                  <% end %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>