config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "mains#index"
  resources :mains, only: :index
  resources :users, only: [:show, :edit, :update]
  resources :staffs
  resources :hair_styles
  resources :reservations, only: [:index, :new, :create, :show]
  resources :news
end

app/models/new.rb
class New < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :content
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_news, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:new, :create, :edit, :update, :destroy]

  def index
    @news = New.order('updated_at DESC').page(params[:page]).per(5)
  end

  def new
    @new = New.new
  end

  def create
    @new = New.new(new_params)
    if @new.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @new.update(new_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    @new.destroy
    redirect_to action: :index
  end

  private

  def new_params
    params.require(:new).permit(:title, :content).merge(user_id: current_user.id)
  end

  def find_news
    @new = New.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.admin?
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/edit.html.erb
<%= render 'shared/header' %>

<div class="contents row">
  <h2>Edit News</h2>
  <div class="container">
    <%= form_with model: @new, url: news_path(@new.id), id: 'edit_news', class: 'edit_news', local: true do |f| %>

      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_area :title %>
      </div>

      <div class="field">
        <%= f.label :content %><br />
        <%= f.text_area :content %>
      </div>

      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/news/index.html.erb
<%= render 'shared/header' %>

<div class="news">
  <h1 class="news-title">NEWS</h1>
  <table class="news-table">
    <tr>
      <th class="left-th">更新日</th> <th class="right-th">タイトル</th>
    </tr>
    <% @news.each do |new| %>
      <tr>
        <td class="left-td"><%= new.updated_at.strftime("%Y.%m.%d") %></td> <td class="right-td"><%= link_to new.title, news_path(new.id) %></td>
      </tr>
    <% end %>
  </table>

  <%= paginate @news %>

  <% if user_signed_in? && current_user.admin? %>
    <div class='create-btn'>
      <%= link_to 'Create', new_news_path %>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>

app/views/news/new.html.erb
<%= render 'shared/header' %>

<div class="contents row">
  <h2>Create News</h2>
  <div class="container">
    <%= form_with model: @new, url: news_index_path, id: 'new_news', class: 'new_news', local: true do |f| %>

      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_area :title %>
      </div>

      <div class="field">
        <%= f.label :content %><br />
        <%= f.text_area :content %>
      </div>

      <div class="actions">
        <%= f.submit "Addition" %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/news/show.html.erb
<%= render 'shared/header' %>

<div class="news-details">
  <h1 class="news-title">NEWS</h1>
  <div class="news-detail">
    <div class="news-detail-date">
      <%= @new.updated_at.strftime("%Y.%m.%d") %>
    </div>
    <div class="news-detail-title">
      <%= @new.title %>
    </div>
    <div class="news-detail-content">
      <%= @new.content %>
    </div>
  </div>
  
  <% if user_signed_in? && current_user.admin? %>
    <div class="news-detail-btn">
      <div class='edit-delete-btn'>
        <%= link_to 'Edit', edit_news_path(@new.id) %>
      </div>
      <div class='edit-delete-btn'>
        <%= link_to 'Delete', news_path(@new.id), method: :delete %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>