config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "mains#index"
  resources :mains, only: :index
  resources :users, only: [:show, :edit, :update]
  resources :staffs
  resources :hair_styles
  resources :reservations, only: [:index, :new, :create, :show]
  resources :news
end

app/models/hair_style.rb
class HairStyle < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :genre

  with_options presence: true do
    validates :style_name
    validates :gender_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :genre_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :images
  end
end

app/controllers/hair_styles_controller.rb
class HairStylesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_hair_style, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:new, :create, :edit, :update, :destroy]

  def index
    @hairs = HairStyle.order('genre_id ASC')
  end

  def new
    @hair = HairStyle.new
  end

  def create
    @hair = HairStyle.new(hair_params)
    if @hair.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @hair.update(hair_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    @hair.destroy
    redirect_to action: :index
  end

  private

  def hair_params
    params.require(:hair_style).permit(:style_name, :gender_id, :genre_id, images: []).merge(user_id: current_user.id)
  end

  def find_hair_style
    @hair = HairStyle.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.admin?
  end
end

app/helpers/hair_styles_helper.rb
module HairStylesHelper
end

app/views/hair_styles/edit.html.erb
<%= render 'shared/header' %>

<div class="contents row">
  <h2>Edit HairStyle</h2>
  <div class="container">
    <%= form_with model: @hair, url: hair_style_path, id: 'edit_hair_style', class: 'edit_hair_style', local: true do |f| %>

      <div class="field">
        <%= f.label :images %><br />
        <%= f.file_field :images, name: 'hair_style[images][]', data: {index: 0} %>
        <%= f.file_field :images, name: 'hair_style[images][]', data: {index: 1} %>
        <%= f.file_field :images, name: 'hair_style[images][]', data: {index: 2} %>
      </div>

      <div class="field">
        <%= f.label :style_name %><br />
        <%= f.text_area :style_name %>
      </div>

      <div class="field">
        <%= f.label :gender %><br />
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"gender-select"}) %>
      </div>

      <div class="field">
        <%= f.label :genre %><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>

      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/hair_styles/index.html.erb
<%= render 'shared/header' %>

<div class="hair-styles">
  <h1 class="hair-style-title">HAIR STYLE</h1>
  <div class="ladies-hair">
    <h2 class="gender-title">MENS</h2>
    <div class="style-box">
      <% @hairs.each do |hair| %>
        <% if hair.gender_id == 2 %> 
          <div class="hair-style">
            <div class="hair-style-image">
              <%= link_to image_tag(hair.images[0], class:"style-img"), hair_style_path(hair.id) %>  
            </div> 
            <div class="hair-style-name">
              <i class="fa-solid fa-scissors"></i><%= hair.style_name %>
            </div>
            <div class="hair-style-genre">
              <i class="fa-solid fa-tag"></i><%= hair.genre.name %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="mens-hair">
    <h2 class="gender-title">LADIES</h2>
    <div class="style-box">
      <% @hairs.each do |hair| %>
        <% if hair.gender_id == 3 %> 
          <div class="hair-style">
            <div class="hair-style-image">
              <%= link_to image_tag(hair.images[0], class:"style-img"), hair_style_path(hair.id) %>  
            </div> 
            <div class="hair-style-name">
              <i class="fa-solid fa-scissors"></i><%= hair.style_name %>
            </div>
            <div class="hair-style-genre">
              <i class="fa-solid fa-tag"></i><%= hair.genre.name %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% if user_signed_in? && current_user.admin? %>
    <div class='create-btn hair-create'>
      <%= link_to 'Create', new_hair_style_path %>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>

app/views/hair_styles/new.html.erb
<%= render 'shared/header' %>

<div class="contents row">
  <h2>Create HairStyle</h2>
  <div class="container">
    <%= form_with model: @hair, url: hair_styles_path, id: 'new_hair_style', class: 'new_hair_style', local: true do |f| %>

      <div class="field">
        <%= f.label :images %><br />
        <%= f.file_field :images, name: 'hair_style[images][]', data: {index: 0} %>
        <%= f.file_field :images, name: 'hair_style[images][]', data: {index: 1} %>
        <%= f.file_field :images, name: 'hair_style[images][]', data: {index: 2} %>
      </div>

      <div class="field">
        <%= f.label :style_name %><br />
        <%= f.text_area :style_name %>
      </div>

      <div class="field">
        <%= f.label :gender %><br />
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"gender-select"}) %>
      </div>

      <div class="field">
        <%= f.label :genre %><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>

      <div class="actions">
        <%= f.submit "Addition" %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/hair_styles/show.html.erb
<%= render 'shared/header' %>

<div class="hair-style-details">
  <h1 class="hair-style-title">HAIR STYLE</h1>
  <div class="hair-style-detail">
    <div class="top-detail">
      <div class="left-hair-image">
        <%= image_tag @hair.images[0], class: "main-hair-image" %>
        <h2>FRONT</h2>
      </div>
      <div class="right-hair-image">
        <%= image_tag @hair.images[1], class: "sub-hair-image" %>
        <h2 class="side-image-title">SIDE</h2>
        <%= image_tag @hair.images[2], class: "sub-hair-image" %>
        <h2>BACK</h2>
      </div>
    </div>
    <div class="bottom-detail">
      <div class="style-name">
        <i class="fa-solid fa-scissors"></i><%= @hair.style_name %>
      </div>
      <div class="style-genre">
        <%= @hair.gender.name %> / <%= @hair.genre.name %>
      </div>
    </div>
  </div>
  <% if user_signed_in? && current_user.admin? %>
    <div class="hair-style-detail-btn">
      <div class='edit-delete-btn'>
        <%= link_to 'Edit', edit_hair_style_path(@hair.id) %>
      </div>
      <div class='edit-delete-btn'>
        <%= link_to 'Delete', hair_style_path(@hair.id), method: :delete %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %> 